stages:
  - deploy
  - test

deploy:
  stage: deploy
  image: fabianmartin/php-symfony

  variables:
    DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db

  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
      - app/config/parameters.yml
      - var/bootstrap.php.cache

  before_script:
    - composer config cache-files-dir /cache/composer

  cache:
    paths:
      - /cache/composer
      - ./vendor

  script:
    - composer install
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n

test:
  stage: test

  script:
    - bin/phpunit
